version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint-tsx
            - run: npm run lint-css
            - run: npm run build
  deploy:
    machine:
      macos:
        xcode: '9.0'
    steps:
      - run:
          command: curl -X POST -d {} ${NETLIFY_HOOK}

workflows:
version: 2
build:
  jobs:
    - build
    - deploy:
        filters:
          branches:
            only: master
