version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint-tsx
            - run: npm run lint-css
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          command: curl -X POST -d {} ${NETLIFY_HOOK}
workflows:
  build:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
